apiVersion: v1
kind: Service
metadata:
  name: backend-service-tls
spec:
  selector:
    app: backend-tls
  type: LoadBalancer
  ports:
    - name: http
      port: 443
      targetPort: 8443
      protocol: TCP
