apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  volumes:
    - name: "backend-data"
      hostPath:
        path: "/var/lib/backend"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      volumeMounts:
        - mountPath: "/data"
          name: "backend-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
